name: icfree-ml
channels:
  - conda-forge
dependencies:
  - python >=3.8,<3.12
  - pandas
  - numpy
  - pyDOE2
  - openpyxl
  - statsmodels
  - matplotlib-base
  - scikit-learn
  - seaborn
  - xgboost
  - scipy
  - ipython
  - ipywidgets 
  - glob2  
  - pip
  - pip:
    - warnings
